language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - sudo apt-get update
    - pip install --upgrade pip

install: 
    - pip install requests os
    
script:
    - python test.py
