language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
cache: pip
install: 
    - pip install requests
    - pip install unittest
    - pip install os
    
script:
    - python test.py