language: python
python:
    - "2.7"
    - "3.5"

before_install:
    - sudo apt-get update
    - pip install --upgrade pip

install:
    - pip install -r requirements.txt  
before_script:
    - flake8 -v --count .  
script:
    - python test.py
